name: Frontend Continuous Integration

on:
  pull_request:
    branches: ["main"]
    paths:
      - "starter/frontend/**"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: starter/frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./starter/frontend
        run: npm ci

      - name: Run linting
        working-directory: ./starter/frontend
        run: npm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: starter/frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./starter/frontend
        run: npm ci

      - name: Run tests
        working-directory: ./starter/frontend
        run: CI=true npm test